var listofanimes=[
    "Naruto",
"Fairy tail",
"Seikoku no Doraguna",
"Hosizora e kakaru hashi",
"seirei tsukei no bureidodansu",
"zero no tsukaima",
"sakura sou no pet kanojo",
"yamada-kun no 7 min no majo",
"isekai wa sumatopon",
"re zero",
"seiren",
"Maid-sama",
"koi to sakyo to chocolate",
"masamune-kun no revenge",
"campiogne",
"hundred",
"Rakudai kishi no cavalry",
"roku de nashi majutsu koushi to akashic records",
"sword art online",
"strike the blood",
"nijiro days",
"trinity seven",
"seiken tsukai no world break",
"gakusen toshi asterix",
"gamers!",
"aoharu ride",
];

var randomItem = listofanimes[Math.floor(Math.random()*listofanimes.length)];
 console.log("pen.js")